import { Hero } from './components/Hero/hero';
import Allproducts from './components/Products/Allproducts';
import DiscountBanner from './components/Products/DiscountBanner';
import FlashSale from './components/Products/FlashSale';
import HotProduct from './components/Products/Hotproduct';
import NewProducts from './components/Products/NewProducts';

 export const metadata = {
   title: "WOWNEX",
   description: "Generated by create next app",
 };

export default async function Home() {

  return (
    <main>
      {/* <Navbar /> */}
      <Hero />
      <FlashSale />
      <HotProduct />
      <NewProducts />
      <DiscountBanner />
      <Allproducts />
      {/* <Footer /> */}
     
    </main>
  );
}
